### ISSUE TITLE
Framework connection broken?

### ISSUE THREAD

**Issue by draumaz** [catboy6969/catboy6969#2]
Hi there, I was trying to link the catboy6969 API to my Raspberry Pi to create a Lovecraftian abomination with sentience like that of the original catboy6969. But I'm finding an issue while flashing the soul onto it.

- Random screaming
- Bleeding from all orifices
- Soulless eyes
- JVM memory leaks

Does anyone have any solutions? I'm getting worried. My boyfriend doesn't want to stay over anymore because of how long this is taking.

Thanks.

**Comment by catboy6969** [comment]
Please leave your hardware information more specifically. What raspberry pi version are you using.
